### ISSUE TITLE
Implement score-interpolation

### ISSUE THREAD

**Issue by buttercutter** [pinellolab/DNA-Diffusion#75]
**GOAL** :  Implements score-interpolation described in [Continuous diffusion for categorical data](https://arxiv.org/abs/2211.15089)

Please see Figure 3 below for overall implementation picture requirements.

![image](https://user-images.githubusercontent.com/3324659/220502514-a96f001f-5b99-4d41-9e63-8d48b70cb203.png)

Up-to-date notebook progress could be found at https://github.com/pinellolab/DNA-Diffusion/blob/score_interpolation_latest/notebooks/experiments/conditional_diffusion/dna_diff_baseline_conditional_UNET.ipynb , click on `history` button to check actual code commits modifications.

**DONE** : 

1. Added [DPM-Solver++](https://arxiv.org/abs/2211.01095) `ODE solver` block
2. Added `Interpolate Embeddings` block
3. Added reparameterization trick for `p_losses()`
4. Fed the output of `Time Embedding` stage into `LayerNorm` inside Unet model

**TODO** : 

- [x] Enable the `self_conditioning`  [logic](https://arxiv.org/abs/2208.04202) properly without runtime dimension issue

- [x] Verify the `Interpolate Embeddings` block

- [ ] Verify that the `LearnedSinusoidalPosEmb` class is actually following the [theoretical concept](https://gregorygundersen.com/blog/2019/12/23/random-fourier-features/) behind `Random Fourier Embedding` block

- [ ] Enable the initial denoising inside `p_losses()` properly considering the actual `mean` and `std` at denoising timestep `t=0`

- [x] Implement all aspects of `Input embedding` stage properly for the `Interpolate scores` block

- [ ] Enhance the denoising process with `noise = sigma * epsilon` where `sigma` is a learned NN parameter, such that the noise will be a deterministic function of the input and the parameter rather than being independent and randomly generated as suggested by chatGPT
- [ ] Verify the integration of `Time Embedding` stage into `Unet` model
- [ ] Enhance the training pipeline using [modified version of tweedie formula in soft-diffusion paper](https://www.linkedin.com/posts/feiphung_diffusion-stablediffusion-deeplearning-activity-7031168716155326464-a2OC/)

**Comment by LucasSilvaFerreira** [comment]
hi @buttercutter, How is the progress on this task? Do you guys already have a prototype running in such a way that we can check the metrics?
